### PR TITLE
Fix typo in pip keyword

### PR DESCRIPTION
**Pull request by jvadair**

### CODE REVIEW

**Comment by CarterKJ** [comment]
*pip3 uninstall pyntree

**Comment by jvadair** [comment]
Error in word: "pyntree" -> deeprai

**Comment by CarterKJ** [comment]
Let me check corporate on this pr.

**Comment by CarterKJ** [comment]
they said no..

**Comment by jvadair** [comment]
Don't forget to run unit tests, though it should pass

**Pull request closed without merging**
